[package]
name = "Pathfinding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
uid = "0.1.7"
bevy_egui = "0.19.0"
rand = "0.8.5"
bevy_mod_picking = "0.11.0"